### ISSUE TITLE
Connected vibrators no longer responding

### ISSUE THREAD

**Issue by Renarikun** [runtime-shady-backroom/buttplug-lite#122]
**Describe the bug**
Vibrators connected to Buttplug Lite will display a solid status light and no longer respond to any command until disconnected from Buttplug Lite.

**To Reproduce**
1. Start Buttplug Lite client
2. Power on vibrator devices.
3. Verify connected devices connect and show in Buttplug Lite client. (Tested Gush and Diamo)
4. Observe status light change on Lovense devices from blinking to solid.
5. Send commands via the appropriate websocket (3031, in this case)
6. After no response from Lovense device, shutdown Buttplug Lite client.
7. Device will resume blinking status light and properly connect to other clients (Intiface & Lovense App)

**Expected behavior**
Expect Buttplug Lite client to connect and control Lovense devices.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Buttplug Lite Version: 2.4.1

**Additional context**
This worked fine only a few days ago, not sure if something changed in the windows bluetooth or the way websockets are run.
I usually use my devices via Resonite with a Vibe Panel (by Beaned) but even other panels and manual commands will no longer work.
The panel still receives the connected device info from Buttplug.io, so there is definitely some types of communication, just no command to the Lovense toys.

**Comment by runtime-shady-backroom** [comment]
I'm unable to reproduce this behavior on buttplug-lite 2.4.1 on Windows 10. You should have logs saved in `%APPDATA%\runtime-shady-backroom\buttplug-lite\data\logs`. Please check your recent log files for anything that looks out of the ordinary. You can also try enabling more verbose logging by running buttplug-lite with the `--verbose` command-line argument and see if that yields anything interesting. I'm happy to look at your logs if you attach them, but note that they contain hardware IDs such as MAC address for connected peripherals. Not a big deal in my personal opinion, but potentially something you'd want to redact.

Also, if you want to try a pre-release build of buttplug-lite 2.5.0, there's one available [here](https://github.com/runtime-shady-backroom/buttplug-lite/actions/runs/6856673243 (scroll all the way to the bottom to download the build artifact for Windows)). There's nothing major changed on my side, but I've updated the dependencies that handle bluetooth and talking to devices so it's possible that something was fixed there.

**Comment by Renarikun** [comment]
There seems to be some strange behaviors specifically with Resonite.  Your 2.5 update fixed something in addition to me tearing apart the proto flux that was converted on the vibe panel.  The strange part is that I opened it changed nothing repacked it and somehow just that active it recompiling fixed the issue.  The strange part is if I go back and load 2.4.1, it works now too.  It's like web sockets got stuck in one of the patches for Resonite.

**Comment by Renarikun** [comment]
I haven't been able to reproduce issue again on 2.4.1 since using 2.5.
