### ISSUE TITLE
Lovense Connect

### ISSUE THREAD

**Issue by BlueTera** [runtime-shady-backroom/buttplug-lite#169]
It would be very nice if this could work with Lovense connect so multiple devices can work with it.

**Comment by runtime-shady-backroom** [comment]
I'm a bit confused. Multiple devices already work (the screenshot in the readme has 4 devices connected. Also, I already have buttplug's lovense connect support enabled in my code. If it's not working I'll probably have to ask qdot if I'm missing some important setup step.
