### ISSUE TITLE
API for device status, battery, and signal strength

### ISSUE THREAD

**Issue by runtime-shady-backroom** [runtime-shady-backroom/buttplug-lite#2]
Someone may have a use case for this. 

Fitting with the theme, a simple easy-to-parse protocol needs to be worked out.

**Comment by jeanahelver** [comment]
simple way for neos would be individual get string requests.
alternatively returning a float3 `[0.0; 0.5; 0.75]` could be send back over the websocket.
parsing and unpacking it we could get battery from x, signal strength from y, and any status code from z (unsure what exactly device status would be)

have heard from a couple of people they really wanting to know how low there battery is.

**Comment by runtime-shady-backroom** [comment]
I believe this is the main use case addressed, so I'm closing this. If people also need a signal strength API we can create a new issue to track that.
