### ISSUE TITLE
Duplicate device support

### ISSUE THREAD

**Issue by runtime-shady-backroom** [runtime-shady-backroom/buttplug-lite#3]
Identically named devices are not currently supported. Without some sort of support for a unique device identifier from the buttplug-rs library, this will be functionally impossible to do in a way that remains consistent between application runs.

**Comment by jeanahelver** [comment]
is there no way to obtain some sort of serial number or uuid from the bluetooth directly?

**Comment by runtime-shady-backroom** [comment]
the buttplug library intentionally doesn't expose bluetooth IDs to users: https://github.com/buttplugio/buttplug/issues/168#issuecomment-511019848

**Comment by runtime-shady-backroom** [comment]
I haven't forgotten about this issue. Soon Buttplug v6 should have a couple of features that make this possible. Buttplug is going to add a user configuration that will make [`ButtplugClientDevice.index()`](https://docs.rs/buttplug/latest/buttplug/client/device/struct.ButtplugClientDevice.html#method.index) return consistent numbers across server restarts. Once that's done, I'll be able to leverage it to uniquely identify devices.

**Comment by runtime-shady-backroom** [comment]
I have devised an absolutely evil hack by which I can obtain some sort of serial number or UUID. For now it's only logging the data, just to prove it works. There's more work to do in order to actually get everything rigged up properly.

I'm honestly not sure if this is a feature people want, though. I've heard from a grand total of zero people with stories about how they have a pile of identical toys they're trying to drive.
