### ISSUE TITLE
Configuration GET request

### ISSUE THREAD

**Issue by Beaned2000** [runtime-shady-backroom/buttplug-lite#9]
It would be nice if we could do a GET request for getting the config details of all the motors.
The Value's i would like to get per motor are:
- Tag
- Device name
- Feature type (e.g. Vibration, Contraction, Rotation ...)

This would be similar to what is already stored in the config file in AppData

The formatting for it shouldn't matter too much but just something that would be nice to parse in Neos

**Comment by runtime-shady-backroom** [comment]
How do you feel about a GET to `http://localhost:3031/deviceconfig` that yields something like this?

```
o;Lovense Edge;vibration
c;Lovense Max;contraction
i;Lovense Edge;vibration
m;Lovense Max;vibration
```

I've opted for `;` as a delimiter as it's already a reserved character in the protocol.

**Comment by Beaned2000** [comment]
Yes! this would be perfect and simple so not too many parsing nodes would be required. thank you

**Comment by runtime-shady-backroom** [comment]
Added in [0.7.0](https://github.com/runtime-shady-backroom/buttplug-lite/releases/tag/0.7.0). The readme has been updated with documentation for the new route.
